### PR TITLE
Account for bytestring newlines in lineno

### PR DESCRIPTION
**Pull request by rshipp**
This corrects the specific problem reported in #35, but there may be other places we're missing newlines as well.

### CODE REVIEW

**Comment by utkonos** [comment]
Ugh. Github is broken at the moment and not usable. I'll come back later and sort this out. The Github UI is unusable at the moment.

**Comment by utkonos** [comment]
Looks like travis won't run if the .travis file is the only change. According to the following, one must close and reopen the PR. Sorry if you all get extra email alerts about this.

https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by rshipp** [comment]
If you're just trying to read the file, it should work like this: https://github.com/plyara/plyara/blob/master/tests/unit_tests.py#L16-L17

Looks like your earlier commit just had a typo in the filename "newlines" instead of "newline": https://github.com/plyara/plyara/pull/36/commits/c89c84509688850db5f081863e18842b0c3e1248

**Comment by utkonos** [comment]
Good catch!

**Comment by utkonos** [comment]
Fixes #35

**Pull request merged**
