### PR TITLE
YARA 4.0.0 Compatibility

### PR DESCRIPTION
**Pull request by malvidin**
This pull adds in base64 and xor keywords, along with additional validation of string modifiers.

### CODE REVIEW

**Comment by utkonos** [comment]
@malvidin Thanks for the PR! Give me a sec to check it over.

**Comment by utkonos** [comment]
@malvidin I am still working on reviewing the PR. Unfortunately, I have been wrestling with Travis CI failing to automatically check this PR and the other one that is open. There are a number of problems with this PR that the linter is finding.

I have opened a ticket with Github support to figure out why the CI tests are not running or even listed under the "all checks" list. Please bear with me while this gets fixed. I'll circle back to review once the CI is no longer broken.

**Comment by utkonos** [comment]
@malvidin I have not been able to determine why the CI checks are not showing here on this list of checks to pass. I'm still working on getting this fixed.

In the mean time, can you please take a look at the unit test failures on the builds for your two PRs:
https://travis-ci.org/github/plyara/plyara/pull_requests

I hope to get these checks displayed here in the PRs again asap.

**Comment by tlansec** [comment]
As far as I can tell all of the bugs reported in Travis CI are around code styling and not functionality? Am I misreading something?

Until this is fixed, if you're reading this and looking for a fix, just pull and build the PR for this issue:

https://github.com/malvidin/plyara/tree/xor_bytes

**Comment by utkonos** [comment]
@tlansec This PR has been merged. Will be cutting a new version asap. Thanks!

**Comment by tlansec** [comment]
Thanks for the heads up - I appreciate all the hard work you put into this project.

**Pull request merged**
