### PR TITLE
Update Rule Hashing

### PR DESCRIPTION
**Pull request by malvidin**
Updated rule hashing, and fixed issues that impacted hashes of the test rules.

### CODE REVIEW

**Comment by utkonos** [comment]
@malvidin Thanks for the PR! I will review this shortly.

**Comment by utkonos** [comment]
@malvidin Please resolve the various conflicts in this PR as well as any CI problems. As soon as this passes CI, I'll merge it.

**Comment by utkonos** [comment]
@malvidin With a drastic change in the hashing, I think it would be wise to add a versioning system to the hashes. Hashes generated with the current code would be acceptable without a version, or with version 1. This new hashing code in this PR generates version 2 hashes. This also leaves everything open to further breaking changes without causing confusion and headaches downstream. Here is my proposal:

Version 1 hashes (both acceptable as indicating version 1):
00567f292137497bc2b9c234b8e80d53aa9ae6e549c03ed3b6dfd71d684747b3
1:00567f292137497bc2b9c234b8e80d53aa9ae6e549c03ed3b6dfd71d684747b3

Version 2 hash:
2:373ef4ea5952433e6ec8a1ea7c5bda6e4edd69d62d6f2dbee68d2c8b9a760713

Thoughts?

**Comment by malvidin** [comment]
My intent with the pull request was increasing the coverage determining when conditions are functionally identical, which necessitates a change in the hash result.

If maintaining backward compatibility for the hash output is necessary, I recommend keeping generate_logic_hash with a notice or deprecation warning, and creating a new function generate_hash that includes these enhancements.

In the slyara code, I created objects for the strings and condition options, so each condition portion can be dumped in a sorted manner by calling my_rule.generate_hash().

**Comment by utkonos** [comment]
> If maintaining backward compatibility for the hash output is necessary, I recommend keeping generate_logic_hash with a notice or deprecation warning, and creating a new function generate_hash that includes these enhancements.

Yes, can you modify the PR to implement this change?

> In the slyara code, I created objects for the strings and condition options, so each condition portion can be dumped in a sorted manner by calling my_rule.generate_hash(). It is not complete, as mentioned in issue #15
> 
> In either case, a more deliberate choice may need to be made on how the conditions are represented, how strings are used to enrich the condition, and if different versions of plyara and slyara must maintain compatibility on the hexdigest output over discrimination between modifications to a rule that may change what content the rule matches.

I'm adding some comments to #15 about the above. We can separate the update to SLY from this PR.

**Comment by cccs-gm** [comment]
@malvidin I have a question about the generate_hash() function. I apologize if this is not the appropriate place to ask this question.

When your function deals with something like 'all of ($a*)' it produces something like this:
`<class 'list'>: ['all', 'of', '(', '<STRINGVALUE>12347891432789014327890143278901432790 | HashTesting | RandomStringOfCharactersasdf;jl1@#$!#@$ | StringB', ')']`

But something like 'all of ($a1, $a2, $a3, $a4)' produces this:
``<class` 'list'>: ['all', 'of', '(', '<STRINGVALUE>12347891432789014327890143278901432790', ',', '<STRINGVALUE>HashTesting', ',', '<STRINGVALUE>RandomStringOfCharactersasdf;jl1@#$!#@$', ',', '<STRINGVALUE>StringB', ')']`

Is there a reason I am missing for not building $a* into a list of '<STRINGVALUE>*'  joined with ','? That would result in generating identical hashes for these sets of strings and conditions.

**Pull request merged**
