### PR TITLE
Code overhaul: version 2.0

### LINKED ISSUE #43: Change python types from optional to standard.
The new python types returned by the optional flags should be the standard output rather than an option.

I suggest this change to be added to a feature list for 2.0.

### PR DESCRIPTION
**Pull request by utkonos**
Fixes #43  among many other items.

### CODE REVIEW

**Comment by utkonos** [comment]
@rshipp I've imported all rules from the YARA project's own unit tests and added coverage for them in our unit tests. I think this should be sufficient to show that we're at least not crashing on something from a rule. I would like to get granular and check the output vs expected output, but that's a huge project. I think this should be sufficient to test this PR.

That being said, please everyone: test this branch against your production rulesets and let me know the results.

**Comment by utkonos** [comment]
@Taskr The deprecation warning and keeping the staticmethods is a great idea. I'll add that now.

**Comment by utkonos** [comment]
This last commit Fixes #46

**Comment by rshipp** [comment]
I ran this over a rule corpus, and it completed with no errors. Diffing the output from the two versions, I'm not seeing anything stand out as incorrect.

Is this change in the metadata output format intentional?

```diff
<         "metadata": {
<             "Author": "Example", 
<             "Category": "Example", 
---
>         "metadata": [
>             {
>                 "Author": "Example"
>             },
>             {
>                 "Category": "Example"
>             },
```

I prefer the older version, a list of dicts is harder to handle than just having the meta section come out as a dict itself.

**Comment by Taskr** [comment]
I'm assuming that the change was made to maintain metadata ordering. I can see where that might be useful.

**Comment by rshipp** [comment]
Ah, interesting, that does make sense. In that case, I'm happy with this branch. Are we sticking with Feb 1 as the release date? I can set a reminder to publish version 2.0.0 on that day.

**Comment by utkonos** [comment]
That was my thinking in making that change.

1. It brings the format in line with the strings section.
2. It facilitates rule rebuilding.

There are two competing use cases here: rule knowledge and rule rebuilding. I had been using plyara for rule knowledge, and the old way of returning the meta section was easier for an end user to perform get statements and return what they need. However, I know that the strings section is a list of dictionaries. Therefore, uses already should have a code snippet for handling getting at data in that section. So, I made the meta section return the same type of structure: a list of dictionaries. This facilitates rule rebuilding and shouldn't sacrifice too much on the user's end.

**Comment by utkonos** [comment]
Also, yes: let's stick with Feb 1 as the release date. It would be good to get feedback from @rholloway before release along with any members of the user base. It would also leave time to tighten up documentation.

**Comment by utkonos** [comment]
I wish git would implement a merge interface like FreeBSD's mergemaster. :(

**Comment by rshipp** [comment]
@utkonos I put together a release notes draft, can you take a look and see if I'm missing anything? https://github.com/plyara/plyara/releases/edit/untagged-b9a1c8cce277b0f8e485 (Let me know if this link doesn't work for you, I'm not sure how to share drafts.)

**Comment by rshipp** [comment]
I had to make some small changes, the tests were only passing here because they weren't running. Not sure why codacy reported green on -53% test coverage... I'll see if there's a way to fix that so we don't miss this next time.

**Pull request merged**
