### PR TITLE
Fix setup.py and unit tests to work with Python 3.5

### PR DESCRIPTION
**Pull request by hillu**
Rewrite some implicit object-to-str and bytes-to-str conversions

Simplify some tests, make them more robust by removing a dependency on
dict key ordering.

Update README

### CODE REVIEW

**Comment by rshipp** [comment]
Thanks for the PR! These test changes look good.

I'm not sure we want to officially support 3.5. I can't speak for the other maintainers, but I don't have easy access to a 3.5 environment. I'm not sure when the EOL for 3.5 is, it seems to be in [security-fixes-only mode](https://www.python.org/downloads/release/python-356/) at the moment. If possible, I'd recommend you update your installation to 3.6, as I can't promise we'll be able to maintain 3.5 support going forward.

I think there are two options for this PR:

1. Add 3.5 to the `.travis.yml`, so we can make sure new versions we release still pass tests on this version. If at some point they start to fail, we may remove the advertisement of 3.5 support, depending on how hard the fix is.
2. Revert the mention of 3.5 support in the README, and continue to unofficially support it until it breaks.

If you make one of these changes, I can merge this PR and push out a new patch version.

**Comment by hillu** [comment]
@rshipp I have opted to add Python 3.5 to the Travis configuration.

Python 3.5 is the Python3 flavor shipped with Debian/stretch (9.x) and Ubuntu/xenial (16.04). Debian/stretch will get full security update support for at least another year after buster (10.0) is released later this year, parts of it longer than that through an LTS program. Ubuntu/xenail will get LTS through 2021-04.

**Comment by rshipp** [comment]
Hm, I didn't realize it was such a widespread default, that's unfortunate. There are a few features added in 3.6 that are quite nice to have. We already have [an open issue](https://github.com/plyara/plyara/issues/15) that will break 3.5 support, at some point.

I've pushed v2.0.1 to PyPI with your changes. Hopefully we're able to maintain 3.5 support long enough for more people to have a chance to migrate off it. You're welcome to send another PR if you notice anything else breaking, we appreciate the help.

**Comment by utkonos** [comment]
@hillu Thanks for the PR! I hoped to move past 3.5 due to the poor support for `pathlib`. The changes are perfectly fine, but 3.5 will most likely be left in the dust at some point for these reasons.

Also, just from a best practices perspective, one shouldn't use the OS's default python for use outside of the OS. In my opinion, all python execution should be done in a virtual environment with precise versions and dependencies.

On the subject of python versions available in Ubuntu LTS, Bionic is the version that I am willing to support. We moved to python 3 to get away from the problems with supporting old versions. Bionic and 3.6+ were the platform chosen for this jump.

**Pull request merged**
