### PR TITLE
Add Back Key/Value Output Option for Meta Section Data

### PR DESCRIPTION
**Pull request by utkonos**
This will add the old output format back as an option.

### CODE REVIEW

**Comment by rshipp** [comment]
would you mind adding some tests for this?

**Comment by utkonos** [comment]
> would you mind adding some tests for this?

Can do

**Comment by utkonos** [comment]
@rshipp This PR won't pass the CI push, but it should pass when it's merged with the unittest changes from the other PR.

If you want, merge the other PR, and I'll rebase this one and fix any problems.

**Comment by utkonos** [comment]
Nevermind. I see the other PR is approved. I'll merge it and rebase this one and see if it passes.

**Comment by utkonos** [comment]
Woohoo! All rebasing worked and this PR now passes all tests.

**Pull request merged**
